###
POST http://localhost:8081 /api/homework
Content-Type: multipart/form-data; boundary=b

--b
Content-Disposition: form-data; name="data"; filename="data.json"
Content-Type: application/json

{ "author": "d08f6d5e-e076-4488-bfce-11e8c6486005", "task": "Первое дз" }
--b
Content-Disposition: form-data; name="file"; filename="hw.txt"
Content-Type: text/plain

< hw1.txt
--b--
