###
POST http://localhost:8079/file-storing/api/homework
Content-Type: multipart/form-data; boundary=b

--b
Content-Disposition: form-data; name="data"; filename="data.json"
Content-Type: application/json

{ "author": "4761b24a-6b04-4d5d-bf81-82df4264037d", "task": "task2" }
--b
Content-Disposition: form-data; name="file"; filename="bad_hw2.txt"
Content-Type: text/plain

< bad_hw.txt
--b--
